version: '3'

services:

  app:
    build:
      context: ./node
    container_name: app
    image: rogickmanoel/node-app:prod
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - "3306:3306"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: rogickmanoel/nginx:prod
    tty: true
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - db
      - app


networks:
  node-network:
    driver: bridge
